version: "3"
services:
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  reference-data:
    image: eu.gcr.io/fdk-infra/reference-data:latest
    ports:
      - "8112:8080"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin