---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-concept-harvester
  name: fdk-concept-harvester
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: fdk-concept-harvester
status:
  loadBalancer: {}
